spring.application.name=erp-system
jwt.secret=your_real_secret_key
jwt.expiration=3600000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true


spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
